import jsonfield
from django.db import models

# Create your models here.
class Category(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{str(self.id)} - {str(self.title)}"


class Product(models.Model):
    productType = models.IntegerField(null=True, blank=True)
    asin = models.TextField(primary_key=True)
    domainId = models.IntegerField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    trackingSince = models.IntegerField(null=True, blank=True)
    listedSince = models.IntegerField(null=True, blank=True)
    lastUpdate = models.IntegerField(null=True, blank=True)
    lastRatingUpdate = models.IntegerField(null=True, blank=True) 
    lastPriceChange = models.IntegerField(null=True, blank=True)
    lastEbayUpdate = models.IntegerField(null=True, blank=True)
    imagesCSV = models.TextField(null=True, blank=True)
    rootCategory = models.IntegerField(null=True, blank=True)
    categories = jsonfield.JSONField(null=True, blank=True)
    categoryTree = jsonfield.JSONField(null=True, blank=True)
    parentAsin = models.TextField(null=True, blank=True)
    variationCSV = models.TextField(null=True, blank=True)
    frequentlyBoughtTogether = jsonfield.JSONField(null=True, blank=True)
    eanList = jsonfield.JSONField(null=True, blank=True)
    upcList = jsonfield.JSONField(null=True, blank=True)
    manufacturer = models.TextField(null=True, blank=True)
    brand = models.TextField(null=True, blank=True)
    productGroup = models.TextField(null=True, blank=True)
    partNumber = models.TextField(null=True, blank=True)
    author = models.TextField(null=True, blank=True)
    binding = models.TextField(null=True, blank=True)
    numberOfItems = models.IntegerField(null=True, blank=True)
    numberOfPages = models.IntegerField(null=True, blank=True)
    publicationDate = models.IntegerField(null=True, blank=True)
    releaseDate = models.IntegerField(null=True, blank=True)
    languages  = jsonfield.JSONField(null=True, blank=True)
    model = models.TextField(null=True, blank=True)
    color = models.TextField(null=True, blank=True)
    size = models.TextField(null=True, blank=True)
    edition = models.TextField(null=True, blank=True)
    format = models.TextField(null=True, blank=True)
    features = jsonfield.JSONField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    packageHeight = models.IntegerField(null=True, blank=True)
    packageLength = models.IntegerField(null=True, blank=True)
    packageWidth = models.IntegerField(null=True, blank=True)
    packageWeight = models.IntegerField(null=True, blank=True)
    itemHeight = models.IntegerField(null=True, blank=True)
    itemLength = models.IntegerField(null=True, blank=True)
    itemWidth = models.IntegerField(null=True, blank=True)
    itemWeight = models.IntegerField(null=True, blank=True)
    availabilityAmazon = models.IntegerField(null=True, blank=True)
    availabilityAmazonDelay = jsonfield.JSONField(null=True, blank=True)
    ebayListingIds = jsonfield.JSONField(null=True, blank=True)
    isAdultProduct = models.BooleanField(null=True, blank=True)
    launchpad = models.BooleanField(null=True, blank=True)
    audienceRating = models.TextField(null=True, blank=True)
    newPriceIsMAP = models.BooleanField(null=True, blank=True)
    isEligibleForTradeIn = models.BooleanField(null=True, blank=True)
    isEligibleForSuperSaverShipping = models.BooleanField(null=True, blank=True)
    fbaFees = jsonfield.JSONField(null=True, blank=True)
    variations = jsonfield.JSONField(null=True, blank=True)
    coupon = jsonfield.JSONField(null=True, blank=True)
    promotions = jsonfield.JSONField(null=True, blank=True)
    stats = jsonfield.JSONField(null=True, blank=True)
    salesRankReference = models.BigIntegerField(null=True, blank=True)
    salesRanks = jsonfield.JSONField(null=True, blank=True)
    rentalDetails = models.TextField(null=True, blank=True)
    rentalSellerId = models.TextField(null=True, blank=True)
    rentalPrices = jsonfield.JSONField(null=True, blank=True)
    offers = jsonfield.JSONField(null=True, blank=True)
    liveOffersOrder = jsonfield.JSONField(null=True, blank=True)
    buyBoxSellerIdHistory = jsonfield.JSONField(null=True, blank=True)
    isRedirectASIN = models.BooleanField(null=True, blank=True)
    isSNS = models.BooleanField(null=True, blank=True)
    offersSuccessful = models.BooleanField(null=True, blank=True)
    csv = jsonfield.JSONField(null=True, blank=True)

    def __str__(self) -> str:
        return self.asin
