# Generated by Django 3.2.4 on 2021-06-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rootCategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
    ]
