# Generated by Django 3.2.1 on 2021-07-04 13:05

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210703_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSNDB',
            fields=[
                ('child_category', models.TextField()),
                ('category_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hsn', models.IntegerField(blank=True, null=True)),
                ('bcd', models.FloatField(default=0, validators=[dashboard.models.validate_percentage])),
                ('gst', models.FloatField(default=0, validators=[dashboard.models.validate_percentage])),
                ('custom_health_cess', models.FloatField(default=0, validators=[dashboard.models.validate_percentage])),
                ('additional_duty_of_customs', models.FloatField(default=0, validators=[dashboard.models.validate_percentage])),
                ('additional_cvd', models.FloatField(default=0, validators=[dashboard.models.validate_percentage])),
                ('compensation_cess', models.FloatField(default=0, validators=[dashboard.models.validate_percentage])),
                ('social_welfare_surcharge', models.FloatField(default=0, validators=[dashboard.models.validate_percentage])),
                ('custom_aidc', models.FloatField(default=0, validators=[dashboard.models.validate_percentage])),
                ('excise_aidc', models.FloatField(default=0, validators=[dashboard.models.validate_percentage])),
            ],
        ),
    ]
