# Generated by Django 3.2.1 on 2021-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_hsndb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.IntegerField(choices=[(1, 'com'), (2, 'co.uk'), (3, 'de'), (4, 'fr'), (5, 'co.jp'), (6, 'ca'), (8, 'it'), (9, 'es'), (10, 'in'), (11, 'com.mx')], default=1)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='india_price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
